### ISSUE TITLE
CloudIcons frame rate drops on safari iOS

### ISSUE THREAD

**Issue by franjorub** [magicuidesign/magicui#210] opened 2024-07-10 22:12 UTC
**Describe the bug**

When the cloud icons are on the middle of the screen the frame rate drops significantly. But if you offset the component a little bit it recovers the smoothness. In safari desktop this doesn't happen 

**To Reproduce**
1. Go to https://franjorub.top
2. Scroll down to the CloudIcons

**Expected behavior**
 The icons animation should run in a constant frame rate.

**Screenshots**
https://github.com/magicuidesign/magicui/assets/24401350/a5e38661-3e74-434a-b25b-b44f3d85703b

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone 13 Pro Max]
 - OS: [iOS 17.5.1 (21F90)]
 - Browser [e.g. safari]
 - Version [e.g. 17.5.1]

**Additional context**

Tested on a Mac mini M1 Pro with safari latest but no problems

**Comment by itsarghyadas** [comment] 2024-12-19 09:30
https://magicui.design/docs/components/icon-cloud

You will see that we've also added a warning sign there because, sometimes, it can be resource-heavy, and since it's a third-party library, that could be the issue. I will be closing this issue for now, as we can't really solve or reproduce it ourselves.

**Closed by itsarghyadas** 2024-12-19 09:30 UTC
