### ISSUE TITLE
[multi colors in icons]: /docs/components/icon-cloud

### ISSUE THREAD

**Issue by vishalqalandari903** [magicuidesign/magicui#461] opened 2024-12-22 08:50 UTC
**Describe the solution you'd like**
Previously, the icons were of colors related to tech logo, but now the icons are all gray which is not suiting. I think there should be option to give color if user want to make all icons of same color. 
currently, on my laptop, the icons are colorful but on my iPhone, they are all gray and when I visited magic-ui, all icons are gray in icons-icloud component.

**Comment by wongyat88** [comment] 2024-12-24 03:57
Same case. I already hosted the website for a period of time and the icon is colorful but now the icon color just become black. I 100% confirm no code / library been change or updated.

**Comment by itsarghyadas** [comment] 2024-12-24 15:27
Okay, so this has been happening to you guys too? I thought I had done something wrong. 😂 I guess it's an issue with the third-party library. Someone has already opened a related issue there: https://github.com/teaguestockwell/react-icon-cloud/issues/14

**Comment by dillionverma** [comment] 2024-12-27 16:20
duplicate of #465

**Closed by dillionverma** 2024-12-27 16:20 UTC
