### ISSUE TITLE
[bug]: /docs/components/animated-circular-progress-bar

### ISSUE THREAD

**Issue by myesn** [magicuidesign/magicui#313] opened 2024-09-13 07:27 UTC
**Describe the bug**

The `value` I passed in is an integer, and the final display is a decimal. This should be a matter of JavaScript's computational accuracy.

**To Reproduce**
```
<AnimatedCircularProgressBar
  max={100}
  min={0}
  value={14}
  gaugePrimaryColor="rgb(79 70 229)"
  gaugeSecondaryColor="rgba(0, 0, 0, 0.1)"
/>
```

**Expected behavior**

**Screenshots**

![image](https://github.com/user-attachments/assets/31c82e5e-8ff5-4c3f-9d88-015a2ca528a8)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by itsarghyadas** [comment] 2024-09-18 17:26
Do you know why it behaved like that? Cause our demo component didn't behave like this on the website.

And I see you have made a PR, I will look into it.

**Comment by itsarghyadas** [comment] 2024-11-13 08:18
The issue is fixed now. Thanks for your contribution.

**Closed by itsarghyadas** 2024-11-13 08:18 UTC
