### ISSUE TITLE
[bug]: /docs/components/icon-cloud

### ISSUE THREAD

**Issue by sakthii05** [magicuidesign/magicui#464] opened 2024-12-24 11:05 UTC
**Describe the bug**
The Icons are in default black colour, 

**Expected behavior**
The Icons should be respective to their Icon colour.

**Comment by itsarghyadas** [comment] 2024-12-27 05:13
Hey, we’re aware of this issue. We tried debugging it and discovered it likely comes from a 3rd-party library. We still want to fix this as soon as possible, and we’re actively working on it. Please give us some time to figure out a solution. Thank you for your feedback!

**Comment by dillionverma** [comment] 2024-12-27 16:20
duplicate of #465

**Closed by dillionverma** 2024-12-27 16:20 UTC
