### ISSUE TITLE
[bug]: /docs/components/icon-cloud

### ISSUE THREAD

**Issue by premacharya15** [magicuidesign/magicui#466] opened 2024-12-26 15:10 UTC
**Issue:**

- The Magic UI Icon Cloud initially displays icons in their respective colors, but after some time, all icons revert to a default black color.

**Expected Behavior:**

- Icons should consistently display their respective colors.

Please investigate and resolve this issue. Thank you!

![image](https://github.com/user-attachments/assets/8aeb7514-3164-4f4a-941d-ef17d40c9afa)

![image](https://github.com/user-attachments/assets/fa1a26f6-15a8-4b0b-8fa5-8137758336f7)

**Comment by itsarghyadas** [comment] 2024-12-27 05:13
Hey, we’re aware of this issue. We tried debugging it and discovered it likely comes from a 3rd-party library. We still want to fix this as soon as possible, and we’re actively working on it. Please give us some time to figure out a solution. Thank you for your feedback!

**Comment by dillionverma** [comment] 2024-12-27 16:20
duplicate of #465

**Closed by dillionverma** 2024-12-27 16:20 UTC
