### ISSUE TITLE
[bug]: /docs/templates/saas

### ISSUE THREAD

**Issue by jaredp** [magicuidesign/magicui#385] opened 2024-10-22 18:26 UTC
Hero Video Dialog is broken on a fresh install of the SaaS template

https://github.com/user-attachments/assets/ac2e0e1e-4ed2-439e-a5a3-c8be483c4858

**Comment by aaron-mota** [comment] 2024-10-23 19:47
Omg I've been trying to figure out what was going on all day.  I'm having the same issue.  Can't figure out how to resolve it... it works just fine on the template that I downloaded and didn't alter, but it's not working on my current project where I'm using said template.

I've literally copy/pasted all the code directly from the working template into my project, including the globals.css/etc., and still it doesn't work.

**Comment by aaron-mota** [comment] 2024-10-23 20:10
So it looks like I can pinpoint it to the `tailwindcss` version.

My template that I originally bought is `"tailwindcss": "^3.4.1"`, and my current project is `"tailwindcss": "^3.4.13".

If I change it to `3.4.1` (and remove `node_modules`, `pnpm-lock.yaml`, then `pnpm install` again), it then works in my project.

**Comment by wahibonae** [comment] 2024-11-14 21:39
### What's causing the issue 
I found that the issue is mainly because of the "linear gradient". It works perfectly when you remove the class "[mask-image:linear-gradient(to_bottom,black_30%,transparent)]".

![15854](https://github.com/user-attachments/assets/a62dc565-7a53-41f1-83a7-3ea8c6d044fa)

### Solution:
First Screenshot: I ended up **adding a maskImage attribute to the HeroVideoDialog** in "ui/hero-video-dialog.tsx" and **passing it to the second div parent element** (not the first one).

Second Screenshot: I then added a value to this attribute in the <HeroVideoDialog /> compoenent.

![93167](https://github.com/user-attachments/assets/162ef8a1-c978-4d56-b248-694130013533)

<img width="716" alt="image" src="https://github.com/user-attachments/assets/3edd0bd7-856e-496d-a2c5-80c34d305cb3">

**Comment by wahibonae** [comment] 2024-11-14 21:41
@aaron-mota @jaredp I hope this works for you. I'll try to push a solution to the repo and close this issue!

**Comment by itsarghyadas** [comment] 2024-11-16 18:01
Nice catch but I need to check it further to reproduce the error. Did anyone resolve it, or does the mask-gradient removal solution work?

Also, why do you think it’s causing that odd positioning error?

**Comment by wahibonae** [comment] 2024-11-17 01:07
I investigated the issue further and found the root cause:

The positioning error occurs because the gradient with masks like `mask-image` creates a new stacking context, which is similar to properties like `opacity` and `transform`. And when this is applied to the outer container through the developer's className that we append to it, this new stacking context keeps the `fixed` positioned dialog within its boundaries, rather than positioning it relative to the viewport.

I found an additional solution, so now we have two available solutions: 

1. **Current workaround**: Apply the mask to the inner container (second parent div element) instead of the outer div
   ```tsx
   <div className={cn("relative", className)}>
     <div className={cn("relative cursor-pointer group", maskImage)}>
   ```

2. **New and recommended solution**: Use React's `createPortal` to render the dialog outside the masked container's DOM hierarchy so that the dialog always remains in the global stacking context:
   ```tsx
   createPortal(
     <AnimatePresence>{/* dialog content */}</AnimatePresence>,
     document.body
   )
   ```

The Portal solution is more robust as it allows us to keep the mask on the outer container while ensuring proper dialog behavior by rendering it at the root level, and this bypasses any stacking context issues.

Please let me know what you think, and I'll be happy to open the new PR for the second solution as well! 😁

**Comment by aaron-mota** [comment] 2024-11-19 00:01
React `createPortal` seems to work, but I ended up having to do:
```typescript
{typeof document !== 'undefined' &&
  createPortal(
    <AnimatePresence>
      {isVideoOpen && (
       {/* dialog content */}
      )}
    </AnimatePresence>,
    document.body
  )}
  ```
  
  so it's getting a little grosser

**Comment by dillionverma** [comment] 2024-12-27 16:16
This issue has been addressed in the latest version of the code where we now use 

` <div className="pointer-events-none absolute inset-x-0 -bottom-12 h-1/3 bg-gradient-to-t from-background via-background to-transparent lg:h-1/4"></div>` to create the gradient overlay effect instead of mask-image

Seemed to be the simplest solution which should work across all browsers.

<img width="789" alt="image" src="https://github.com/user-attachments/assets/7f24e267-031d-419f-acc7-cddbe916dbf1" />

Closing issue for now! Let me know if you still come across similar issues!

**Closed by dillionverma** 2024-12-27 16:16 UTC
